### ISSUE TITLE
End of input reached before message was fully decoded

### ISSUE THREAD

**Issue by mmuszkow** [GlobalSign/ASN1.js#11]
Hi,
I'm trying to use your library to parse LDAP responses. After binding, I receive a standard success response: 300c02010161070a010004000400, see https://lapo.it/asn1js/#300C02010161070A010004000400 . Your parser fails on the last element (byteLength = 14, input_offset = 12, input_length = 4), here's the place in code:```javascript
if((input_buffer.byteLength - input_offset - input_length) < 0)
{
    this.error = "End of input reached before message was fully decoded (inconsistent offset and length values)";
    return false;
}```

**Comment by YuryStrozhevsky** [comment]
Seems you had an old version of ASN1js in your tests because on latest version I had another error message. But anyway the bug was because of not fully correct handling of zero-length OCTETSTRING. Fixed in latest release v1.2.2
