### ISSUE TITLE
Context-specific tags?

### ISSUE THREAD

**Issue by DavidSimnerRG** [GlobalSign/ASN1.js#9]
Hi,

I'm using this library for BER encoding, and, because I need to follow a predefined ASN.1 schema, I need to have a context-specific tag.

I'm currently using the code below (which I wrote) to add extra classes that create a constructed context-specific tag, as well as, a non-constructed context-specific tag.

I'm wondering if there's a better way to do this?  I'd rather not extend the API, and by doing so re-invent the wheel.  Given that context-specific tags are a core part of ASN.1, I was expecting that the API would let me create them directly, but I couldn't find or work out the best way to do this, hence the code below.  What have I missed in the API itself?

Thanks! :)

```javascript
    var asn1 = org.pkijs.asn1;

    asn1.CONSTRUCTED_CONTEXT_SPECIFIC = function () {
        asn1.ASN1_CONSTRUCTED.call(this, arguments[0]);
        this.id_block.tag_class = 3;
        this.id_block.tag_number = 0;
    };
    asn1.CONSTRUCTED_CONTEXT_SPECIFIC.prototype = new asn1.ASN1_CONSTRUCTED();
    asn1.CONSTRUCTED_CONTEXT_SPECIFIC.constructor = asn1.CONSTRUCTED_CONTEXT_SPECIFIC;
 
    asn1.PRIMITIVE_CONTEXT_SPECIFIC = function () {
        asn1.ASN1_PRIMITIVE.call(this, arguments[0]);
        this.id_block.tag_class = 3;
        this.id_block.tag_number = 0;
    };
    asn1.PRIMITIVE_CONTEXT_SPECIFIC.prototype = new asn1.ASN1_PRIMITIVE();
    asn1.PRIMITIVE_CONTEXT_SPECIFIC.constructor = asn1.PRIMITIVE_CONTEXT_SPECIFIC;
```

**Comment by YuryStrozhevsky** [comment]
Have you checked https://github.com/GlobalSign/PKI.js? There are many examples of "CONTEXT_SPECIFIC" tags in the library. Also probably you will find the schema you are buillding now.

As for example I can give you this:
```javascript
new in_window.org.pkijs.asn1.ASN1_CONSTRUCTED({
optional: true,
id_block: {
tag_class: 3, // CONTEXT-SPECIFIC
tag_number: 0 // [0]
},
value: [
new in_window.org.pkijs.asn1.INTEGER({ name: (names.tbsCertificate_version || "tbsCertificate.version") }) // EXPLICIT integer value
]
})
```

The example is from "local.tbsCertificate" class, "x509_schema.js" file.

**Comment by DavidSimnerRG** [comment]
Thanks :)

It looks like I want in_window.org.pkijs.schema.CMS_ENVELOPED_DATA

The code I've written is here https://github.com/DavidSimnerRG/web-cryptography-api/blob/master/cms.js which uses the Web Crypto API to create a CMS enveloped data, which BouncyCastle (a C# crypto library) can then decrypt.

**Comment by YuryStrozhevsky** [comment]
Please aware that the "CMS_ENVELOPED_DATA" class is not finished yet: only parsing of data was designed.

**Comment by YuryStrozhevsky** [comment]
Now PKIjs has full-featured support for CMS Enveloped data - encrypt/decrypt and such. For ECC or RSA algorithms.
